config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: 'tasks'
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create', as: 'create_task'
  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save!
    redirect_to task_path(@task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit this task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<!-- app/views/restaurants/index.html.erb -->
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <h2><%= link_to task.title, task_path(task) %></h2>
      <h4><%= link_to "edit", edit_task_path(task) %></h4>
      <h4><%= link_to "delete", destroy_task_path(task), method: :delete %></h4>
    </li>
  <% end %>
</ul>
<%= link_to "create a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Back to all tasks", tasks_path %>